#! /bin/bash

phenix.refine "3hn8.mtz" "strategy=*individual_sites individual_sites_real_space rigid_body *individual_adp group_adp tls *occupancies group_anomalous" "topology_file_name=4amber_3hn8.prmtop" "amber.coordinate_file_name=4amber_3hn8.rst7" "refinement.main.number_of_macro_cycles=10" "write_geo=False" "--overwrite" "md_engine=sander" "4phenix_3hn8.pdb" "output.prefix=EH" "discard_psi_phi=True" "c_beta_restraints=True" "use_amber=False"

phenix.refine "3hn8.mtz" "strategy=*individual_sites individual_sites_real_space rigid_body *individual_adp group_adp tls *occupancies group_anomalous" "topology_file_name=4amber_3hn8.prmtop" "amber.coordinate_file_name=4amber_3hn8.rst7" "refinement.main.number_of_macro_cycles=10" "write_geo=False" "--overwrite" "md_engine=sander" "4phenix_3hn8.pdb" "discard_psi_phi=True" "c_beta_restraints=True" "use_amber=True" "output.prefix=amber_0.05" "wxc_scale=0.05" "discard_psi_phi=False" "c_beta_restraints=False"

phenix.refine "3hn8.mtz" "strategy=*individual_sites individual_sites_real_space rigid_body *individual_adp group_adp tls *occupancies group_anomalous" "topology_file_name=4amber_3hn8.prmtop" "amber.coordinate_file_name=4amber_3hn8.rst7" "refinement.main.number_of_macro_cycles=10" "write_geo=False" "--overwrite" "md_engine=sander" "4phenix_3hn8.pdb" "discard_psi_phi=True" "c_beta_restraints=True" "use_amber=True" "output.prefix=amber_0.025" "wxc_scale=0.025" "discard_psi_phi=False" "c_beta_restraints=False"

phenix.refine "3hn8.mtz" "strategy=*individual_sites individual_sites_real_space rigid_body *individual_adp group_adp tls *occupancies group_anomalous" "topology_file_name=4amber_3hn8.prmtop" "amber.coordinate_file_name=4amber_3hn8.rst7" "refinement.main.number_of_macro_cycles=10" "write_geo=False" "--overwrite" "md_engine=sander" "4phenix_3hn8.pdb" "discard_psi_phi=True" "c_beta_restraints=True" "use_amber=True" "output.prefix=amber_0.075" "wxc_scale=0.075" "discard_psi_phi=False" "c_beta_restraints=False"
