#! /usr/bin/python
import sys
import os
from numpy import *
from Scientific.IO import NetCDF as Net




traj = Net.NetCDFFile(sys.argv[1], 'a')
allcoords=traj.variables['coordinates']
frames=allcoords.shape[0]
print frames


def readmdcrd(filename):
	with open(filename) as f:
		x = f.readlines()
	boxsizeline=x[len(x)-1]
	x=x[1:len(x)-1]  #delete first and last line of file
	coords =[]
	for line in x:
		coords.extend(line.split())
	return coords, boxsizeline
